const CONFIG_CANVAS_WIDTH = 800;
const CONFIG_CANVAS_HEIGHT = 600;
const CONFIG_SPAWN_POINT = {x: 50, y: 50};
const CONFIG_CREATURE_SIZE = 5;
const CONFIG_TARGET_POINT = {x: Math.random() * (CONFIG_CANVAS_WIDTH - 100) + 50, y: Math.random() * (CONFIG_CANVAS_HEIGHT - 100) + 50};
